CREATE SCHEMA IF NOT EXISTS roles;

CREATE TABLE IF NOT EXISTS roles.roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO roles.roles (name)
VALUES
('FLEET_MANAGER'),
('DISPATCHER'),
('SAFETY_OFFICER'),
('FINANCIAL_ANALYST')
ON CONFLICT (name) DO NOTHING;
